[tool.poetry]
name = "sakamata-dpy"
version = "0.1.0"
description = ""
authors = ["sushi-chaaaan <sushi_code@outlook.jp>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
aiodns = "3.0.0"
aiohttp = "3.8.1"
aiosignal = "1.2.0"
async-timeout = "4.0.2"
attrs = "21.4.0"
Brotli = "1.0.9"
cchardet = "2.1.7"
certifi = "2021.10.8"
cffi = "1.15.0"
charset-normalizer = "2.0.12"
discord-handler = "0.0.5"

[tool.poetry.dev-dependencies]
black = "22.3.0"
flake8 = "4.0.1"
click = "8.1.3"
mypy-extensions = "0.4.3"
pathspec = "0.9.0"
platformdirs = "2.5.2"
tomli = "2.0.1"
mccabe = "0.6.1"
pycodestyle = "2.8.0"
pyflakes = "2.4.0"
pip-autoremove = "^0.10.0"
pipdeptree = "^2.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
